on:
  push:
    branches: [ dev ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt

      - name: publish
        run: |
          pelican content -o output -s pelicanconf.py
          ghp-import output
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push gh-pages:master
